version: '3.8'

services:
  ssrf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssrf-lab
    ports:
      - "8091:8080"
    environment:
      - SSRF_PROTECTION=disabled
    restart: unless-stopped

  internal-service:
    image: nginx:alpine
    container_name: ssrf-internal
    volumes:
      - ./internal-data:/usr/share/nginx/html:ro
