version: '3.8'

services:
  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    image: wordpress:5.8.1
    container_name: wordpress-vulnerable
    ports:
      - "8087:80"
    depends_on:
      - wordpress-db
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
    volumes:
      - ./wp-content:/var/www/html/wp-content
    restart: unless-stopped
