version: '3.8'

services:
  docker-escape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-escape
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    restart: unless-stopped
